var _D = exports



_D.SPI_HEADER_SIZE =  				   			(5)
_D.SIMPLE_LINK_HCI_CMND_HEADER_SIZE =  			(4)
_D.HEADERS_SIZE_CMD =         					(_D.SPI_HEADER_SIZE + _D.SIMPLE_LINK_HCI_CMND_HEADER_SIZE)
_D.SIMPLE_LINK_HCI_DATA_CMND_HEADER_SIZE =  		(5)
_D.SIMPLE_LINK_HCI_DATA_HEADER_SIZE =  			(5)
_D.SIMPLE_LINK_HCI_PATCH_HEADER_SIZE =  			(2)


//*****************************************************************************
//
// Values that can be used as HCI Commands and HCI Packet header defines
//
//*****************************************************************************
_D.HCI_TYPE_CMND  =        0x1
_D.HCI_TYPE_DATA =           0x2
_D.HCI_TYPE_PATCH  =       0x3
_D.HCI_TYPE_EVNT    =      0x4


_D.HCI_EVENT_PATCHES_DRV_REQ = 			(1)
_D.HCI_EVENT_PATCHES_FW_REQ = 			(2)
_D.HCI_EVENT_PATCHES_BOOTLOAD_REQ = 		(3)


_D.HCI_CMND_WLAN_BASE  = (0x0000)
_D.HCI_CMND_WLAN_CONNECT = 0x0001
_D.HCI_CMND_WLAN_DISCONNECT =    0x0002
_D.HCI_CMND_WLAN_IOCTL_SET_SCANPARAM =    0x0003
_D.HCI_CMND_WLAN_IOCTL_SET_CONNECTION_POLICY =  0x0004
_D.HCI_CMND_WLAN_IOCTL_ADD_PROFILE = 0x0005
_D.HCI_CMND_WLAN_IOCTL_DEL_PROFILE =   0x0006
_D.HCI_CMND_WLAN_IOCTL_GET_SCAN_RESULTS =  0x0007
_D.HCI_CMND_EVENT_MASK =   0x0008
_D.HCI_CMND_WLAN_IOCTL_STATUSGET = 0x0009
_D.HCI_CMND_WLAN_IOCTL_SIMPLE_CONFIG_START =        0x000A
_D.HCI_CMND_WLAN_IOCTL_SIMPLE_CONFIG_STOP   =      0x000B
_D.HCI_CMND_WLAN_IOCTL_SIMPLE_CONFIG_SET_PREFIX =   0x000C
_D.HCI_CMND_WLAN_CONFIGURE_PATCH =					0x000D


_D.HCI_CMND_SOCKET_BASE   = 0x1000
_D.HCI_CMND_SOCKET=         0x1001
_D.HCI_CMND_BIND    =       0x1002
_D.HCI_CMND_RECV      =     0x1004
_D.HCI_CMND_ACCEPT      =   0x1005
_D.HCI_CMND_LISTEN   =      0x1006
_D.HCI_CMND_CONNECT    =    0x1007
_D.HCI_CMND_BSD_SELECT 	= 0x1008
_D.HCI_CMND_SETSOCKOPT=     0x1009
_D.HCI_CMND_GETSOCKOPT  =   0x100A
_D.HCI_CMND_CLOSE_SOCKET=   0x100B
_D.HCI_CMND_RECVFROM  =     0x100D
_D.HCI_CMND_GETHOSTNAME =   0x1010
_D.HCI_CMND_MDNS_ADVERTISE= 	   0x1011


_D.HCI_DATA_BASE = 								0x80

_D.HCI_CMND_SEND =            					(0x01 + _D.HCI_DATA_BASE)
_D.HCI_CMND_SENDTO =         						(0x03 + _D.HCI_DATA_BASE )
_D.HCI_DATA_BSD_RECVFROM = 						(0x04 + _D.HCI_DATA_BASE )
_D.HCI_DATA_BSD_RECV = 							(0x05 + _D.HCI_DATA_BASE )


_D.HCI_CMND_NVMEM_CBASE = 		(0x0200)


_D.HCI_CMND_NVMEM_CREATE_ENTRY =  (0x0203)
_D.HCI_CMND_NVMEM_SWAP_ENTRY =   	(0x0205)
_D.HCI_CMND_NVMEM_READ =     		(0x0201)
_D.HCI_CMND_NVMEM_WRITE =    		(0x0090)
_D.HCI_CMND_NVMEM_WRITE_PATCH = 	(0x0204)
_D.HCI_CMND_READ_SP_VERSION =   	(0x0207)

_D.HCI_CMND_READ_BUFFER_SIZE  = 0x400B
_D.HCI_CMND_SIMPLE_LINK_START = 0x4000

_D.HCI_CMND_NETAPP_BASE = 		0x2000

_D.HCI_NETAPP_DHCP = 				    (0x0001 + _D.HCI_CMND_NETAPP_BASE)
_D.HCI_NETAPP_PING_SEND =                         (0x0002 + _D.HCI_CMND_NETAPP_BASE)
_D.HCI_NETAPP_PING_REPORT =                       (0x0003 + _D.HCI_CMND_NETAPP_BASE)
_D.HCI_NETAPP_PING_STOP =                         (0x0004 + _D.HCI_CMND_NETAPP_BASE)
_D.HCI_NETAPP_IPCONFIG =                          (0x0005 + _D.HCI_CMND_NETAPP_BASE)
_D.HCI_NETAPP_ARP_FLUSH = 			    (0x0006 + _D.HCI_CMND_NETAPP_BASE)
_D.HCI_NETAPP_SET_DEBUG_LEVEL = 					(0x0008 + _D.HCI_CMND_NETAPP_BASE)
_D.HCI_NETAPP_SET_TIMERS = 						(0x0009 + _D.HCI_CMND_NETAPP_BASE)






//*****************************************************************************
//
// Values that can be used as HCI Events defines
//
//*****************************************************************************
_D.HCI_EVNT_WLAN_BASE  =    0x0000
_D.HCI_EVNT_WLAN_CONNECT =  0x0001
_D.HCI_EVNT_WLAN_DISCONNECT =   0x0002
_D.HCI_EVNT_WLAN_IOCTL_ADD_PROFILE =
                                0x0005


_D.HCI_EVNT_SOCKET        =       _D.HCI_CMND_SOCKET
_D.HCI_EVNT_BIND            =     _D.HCI_CMND_BIND
_D.HCI_EVNT_RECV       =          _D.HCI_CMND_RECV
_D.HCI_EVNT_ACCEPT       =        _D.HCI_CMND_ACCEPT
_D.HCI_EVNT_LISTEN         =      _D.HCI_CMND_LISTEN
_D.HCI_EVNT_CONNECT          =    _D.HCI_CMND_CONNECT
_D.HCI_EVNT_SELECT      =         _D.HCI_CMND_BSD_SELECT
_D.HCI_EVNT_CLOSE_SOCKET  =       _D.HCI_CMND_CLOSE_SOCKET
_D.HCI_EVNT_RECVFROM        =     _D.HCI_CMND_RECVFROM
_D.HCI_EVNT_SETSOCKOPT  =         _D.HCI_CMND_SETSOCKOPT
_D.HCI_EVNT_GETSOCKOPT    =       _D.HCI_CMND_GETSOCKOPT
_D.HCI_EVNT_BSD_GETHOSTBYNAME=    _D.HCI_CMND_GETHOSTNAME
_D.HCI_EVNT_MDNS_ADVERTISE =   _D.HCI_CMND_MDNS_ADVERTISE
 
_D.HCI_EVNT_SEND   =        0x1003
_D.HCI_EVNT_WRITE    =      0x100E
_D.HCI_EVNT_SENDTO     =    0x100F

_D.HCI_EVNT_PATCHES_REQ =     0x1000

_D.HCI_EVNT_UNSOL_BASE =     0x4000

_D.HCI_EVNT_WLAN_UNSOL_BASE =      (0x8000)

_D.HCI_EVNT_WLAN_UNSOL_CONNECT =   	 (0x0001 + _D.HCI_EVNT_WLAN_UNSOL_BASE)
_D.HCI_EVNT_WLAN_UNSOL_DISCONNECT =    (0x0002 + _D.HCI_EVNT_WLAN_UNSOL_BASE)
_D.HCI_EVNT_WLAN_UNSOL_INIT =          (0x0004 + _D.HCI_EVNT_WLAN_UNSOL_BASE)
_D.HCI_EVNT_WLAN_TX_COMPLETE =          (0x0008 + _D.HCI_EVNT_WLAN_UNSOL_BASE)
_D.HCI_EVNT_WLAN_UNSOL_DHCP =          (0x0010 + _D.HCI_EVNT_WLAN_UNSOL_BASE)
_D.HCI_EVNT_WLAN_ASYNC_PING_REPORT =   (0x0040 + _D.HCI_EVNT_WLAN_UNSOL_BASE)
_D.HCI_EVNT_WLAN_ASYNC_SIMPLE_CONFIG_DONE =   (0x0080 + _D.HCI_EVNT_WLAN_UNSOL_BASE)
_D.HCI_EVNT_WLAN_KEEPALIVE = 			 (0x0200  + _D.HCI_EVNT_WLAN_UNSOL_BASE)
_D.HCI_EVNT_BSD_TCP_CLOSE_WAIT =      (0x0800 + _D.HCI_EVNT_WLAN_UNSOL_BASE)

_D.HCI_EVNT_DATA_UNSOL_FREE_BUFF =  
                                0x4100

_D.HCI_EVNT_NVMEM_CREATE_ENTRY =  
                                _D.HCI_CMND_NVMEM_CREATE_ENTRY
_D.HCI_EVNT_NVMEM_SWAP_ENTRY =  _D.HCI_CMND_NVMEM_SWAP_ENTRY

_D.HCI_EVNT_NVMEM_READ =      _D.HCI_CMND_NVMEM_READ
_D.HCI_EVNT_NVMEM_WRITE =     (0x0202)

_D.HCI_EVNT_READ_SP_VERSION =   	
				_D.HCI_CMND_READ_SP_VERSION

_D.HCI_EVNT_INPROGRESS  =   0xFFFF


_D.HCI_DATA_RECVFROM =        0x84
_D.HCI_DATA_RECV =            0x85
_D.HCI_DATA_NVMEM =           0x91

_D.HCI_EVENT_CC3000_CAN_SHUT_DOWN =  0x99

//*****************************************************************************
//
// Prototypes for the structures for APIs.
//
//*****************************************************************************

_D.HCI_DATA_HEADER_SIZE = 		(5)
_D.HCI_EVENT_HEADER_SIZE = 		(5)
_D.HCI_DATA_CMD_HEADER_SIZE = 	(5)
_D.HCI_PATCH_HEADER_SIZE = 		(6)

_D.HCI_PACKET_TYPE_OFFSET = 		(0)
_D.HCI_PACKET_ARGSIZE_OFFSET = 	(2)
_D.HCI_PACKET_LENGTH_OFFSET = 	(3)


_D.HCI_EVENT_OPCODE_OFFSET =  (1)
_D.HCI_EVENT_LENGTH_OFFSET = 	(3)
_D.HCI_EVENT_STATUS_OFFSET = 	(4)
_D.HCI_DATA_LENGTH_OFFSET = 	(3)